UNSEEN_CLASSES = {
    'sketchy_2': [
        'bat',
        'cabin',
        'cow',
        'dolphin',
        'door',
        'giraffe',
        'helicopter',
        'mouse',
        'pear',
        'raccoon',
        'rhinoceros',
        'saw',
        'scissors',
        'seagull',
        'skyscraper',
        'songbird',
        'sword',
        'tree',
        'wheelchair',
        'windmill',
        'window',
    ],
    'sketchy_1': [
        'cup',
        'swan',
        'harp',
        'squirrel',
        'snail',
        'ray',
        'pineapple',
        'volcano',
        'rifle',
        'scissors',
        'parrot',
        'windmill',
        'teddy_bear',
        'tree',
        'wine_bottle',
        'deer',
        'chicken',
        'airplane',
        'wheelchair',
        'tank',
        'umbrella',
        'butterfly',
        'camel',
        'horse',
        'bell',
    ],
    'tuberlin': [
        'banana',
        'bus',
        'tractor',
        'suitcase',
        'streetlight',
        'telephone',
        'bottle opener',
        'canoe',
        'fan',
        'teacup',
        'penguin',
        'laptop',
        'shoe',
        'lighter',
        'hot air balloon',
        'pizza',
        'brain',
        'ant',
        't-shirt',
        'trombone',
        'windmill',
        'snowboard',
        'table',
        'rollerblades',
        'parachute',
        'space shuttle',
        'bridge',
        'frying-pan',
        'bread',
        'horse',
    ],
    'quickdraw': [
        'bat',
        'cow',
        'dolphin',
        'door',
        'giraffe',
        'helicopter',
        'mouse',
        'raccoon',
        'rhinoceros',
        'saw',
        'scissors',
        'skyscraper',
        'tree',
        'windmill',
        'feather',
        'campfire',
        'palm tree',
        'fire_hydrant',
        'bread',
        'beach',
        'megaphone',
        'cactus',
        'zebra',
        'tiger',
        'shark',
        'frog',
        'banana',
        'cake',
        'hamburger',
        'fan',
    ],
}

UNSEEN_CLASSES['sketchy'] = UNSEEN_CLASSES['sketchy_2']
